### ISSUE TITLE
Package a base env ERROR!

### ISSUE THREAD

**Issue by tyut11103** [conda/conda-pack#103]
1. I installed Anaconda.
2. I source activate base
3. I conda pack my base environment,BUT failed。
![image](https://user-images.githubusercontent.com/50626593/75126858-cf6a1180-56f6-11ea-89e5-a30f910f8dc4.png)

When I create a new evn , package is ok. 
Why package the base env failed?
Any answer is appreciate!

**Comment by tyut11103** [comment]
(base) [root@kwephicprd17841 bin]# which conda-pack
/opt/compiledir/nzj/miner_pkgs/anaconda3/output/bin/conda-pack
(base) [root@kwephicprd17841 bin]# conda pack -o mytest2
Collecting packages...
Traceback (most recent call last):
  File "/opt/compiledir/nzj/miner_pkgs/anaconda3/output/lib/python3.7/site-packages/conda_pack/cli.py", line 148, in main
    ignore_editable_packages=args.ignore_editable_packages)
  File "/opt/compiledir/nzj/miner_pkgs/anaconda3/output/lib/python3.7/site-packages/conda_pack/core.py", line 451, in pack
    env = CondaEnv.from_default(ignore_editable_packages=ignore_editable_packages)
  File "/opt/compiledir/nzj/miner_pkgs/anaconda3/output/lib/python3.7/site-packages/conda_pack/core.py", line 165, in from_default
    return cls.from_prefix(name_to_prefix(), **kwargs)
  File "/opt/compiledir/nzj/miner_pkgs/anaconda3/output/lib/python3.7/site-packages/conda_pack/core.py", line 139, in from_prefix
    files = load_environment(prefix, **kwargs)
  File "/opt/compiledir/nzj/miner_pkgs/anaconda3/output/lib/python3.7/site-packages/conda_pack/core.py", line 733, in load_environment
    pkg = info['link']['source']
TypeError: 'NoneType' object is not subscriptable
