### ISSUE TITLE
Install error - ValueError: Unregistered SAT variable name: conda-forge/osx-64::setuptools-46.1.3-py37hc8dfbb8_0

### ISSUE THREAD

**Issue by davidwynter** [conda/conda-pack#107]
Tried to install conda-pack on OSX Version: 10.14.6 (18G4032)

```
✗ conda install -c conda-forge conda-pack
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/logic.py", line 126, in _convert
        return self.names[name]
    KeyError: 'conda-forge/osx-64::setuptools-46.1.3-py37hc8dfbb8_0'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 558, in _add_specs
        (_.to_match_spec() for _ in ssc.prefix_data.iter_records()))), self.specs_to_add
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 1105, in get_conflicting_specs
        C = r2.gen_clauses()
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 909, in gen_clauses
        nkey = C.Not(self.to_sat_name(prec))
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/logic.py", line 145, in Not
        return self._eval(self._clauses.Not, (x,), (), polarity, name)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/logic.py", line 131, in _eval
        args = self._convert(args)
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/logic.py", line 121, in _convert
        return type(x)(map(self._convert, x))
      File "/Users/david/miniconda3/lib/python3.7/site-packages/conda/common/logic.py", line 128, in _convert
        raise ValueError("Unregistered SAT variable name: {}".format(name))
    ValueError: Unregistered SAT variable name: conda-forge/osx-64::setuptools-46.1.3-py37hc8dfbb8_0

`$ /Users/david/miniconda3/bin/conda install -c conda-forge conda-pack`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=horizon_lib
                CONDA_EXE=/Users/david/miniconda3/bin/conda
             CONDA_PREFIX=/Users/david/miniconda3/envs/horizon_lib
           CONDA_PREFIX_1=/Users/david/miniconda3
    CONDA_PROMPT_MODIFIER=(horizon_lib)
         CONDA_PYTHON_EXE=/Users/david/miniconda3/bin/python
               CONDA_ROOT=/Users/david/miniconda3
              CONDA_SHLVL=2
                     PATH=/Users/david/miniconda3/bin:/Users/david/miniconda3/envs/horizon_lib/b
                          in:/Users/david/miniconda3/condabin:/Library/Frameworks/Python.framewo
                          rk/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/
                          bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bi
                          n:/usr/sbin:/sbin:/usr/local/bin:/opt/ImageMagick/bin:/usr/bin:/bin:/u
                          sr/sbin:/sbin:/usr/local/bin:/Users/david/miniconda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : horizon_lib
    active env location : /Users/david/miniconda3/envs/horizon_lib
            shell level : 2
       user config file : /Users/david/.condarc
 populated config files : /Users/david/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/david/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/david/miniconda3/pkgs
                          /Users/david/.conda/pkgs
       envs directories : /Users/david/miniconda3/envs
                          /Users/david/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by mcg1969** [comment]
If afraid this is really a `conda` issue, not a `conda-pack` issue.

That said, I just did `conda install -c conda-forge conda-pack` on my Mac without issue.
