### ISSUE TITLE
No such file or directory for matplotlib: libtcl.so

### ISSUE THREAD

**Issue by ericdill** [conda/conda-pack#99]
Trying to pack up a default Anaconda3 installation to distribute to HDFS results in a file not found for matplotlib:

```
/home/ericdill/miniconda/envs/conda-pack/bin/conda-pack -p /tmp/anaconda3 -o /tmp/anaconda3.zip
Collecting packages...
Packing environment at '/tmp/anaconda3' to '/tmp/anaconda3.zip'
[#######                                 ] | 17% Completed | 10.1s
Traceback (most recent call last):
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/cli.py", line 135, in main
    pack(name=args.name,
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/core.py", line 462, in pack
    return env.pack(output=output, format=format, arcroot=arcroot,
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/core.py", line 333, in pack
    packer.add(f)
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/core.py", line 929, in add
    self.archive.add(file.source, file.target)
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/formats.py", line 207, in add
    self._add(source, target)
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/site-packages/conda_pack/formats.py", line 291, in _add
    self.archive.write(source, target)
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/zipfile.py", line 1739, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/home/ericdill/miniconda/envs/conda-pack/lib/python3.8/zipfile.py", line 521, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/anaconda3/pkgs/matplotlib-3.1.1-py37h5429711_0/lib/libtcl.so'
```

`/tmp/anaconda3` was created by downloading `Anaconda3-2019.10-Linux-x86_64.sh` and installing into `/tmp/Anaconda3`

Seems that libtcl8.6.so does not exist on my machine. this is less of a conda-pack issue and more of a me-not-fully-understanding-conda issue, i think

```
$ ll /tmp/anaconda3/pkgs/matplotlib-3.1.1-py37h5429711_0/lib/libtcl.so
lrwxrwxrwx. 1 ericdill ericdill 12 Aug 23 10:52 /tmp/anaconda3/pkgs/matplotlib-3.1.1-py37h5429711_0/lib/libtcl.so -> libtcl8.6.so
```

I'm not 100% sure what the color coding means but in the above output, `/tmp/anaconda3/pkgs/matplotlib-3.1.1-py37h5429711_0/lib/libtcl.so` is red rext and `libtcl8.6.so` is blinking white text in my standard linux terminal

**Comment by AlbertDeFusco** [comment]
I got it to work by installing the anaconda=2019.10 package.

1. install miniconda (conda 4.8.1)
2. conda install -c defaults -c conda-forge conda-pack=0.4.0
3. conda create -n anaconda3 python=3.7 anaconda=2019.10
4. conda activate anaconda3
5. conda pack -o anaconda3_2019_10.tar.gz

```
conda list matplotlib
# packages in environment at /home/hadoop/miniconda3/envs/anaconda3:
#
# Name                    Version                   Build  Channel
matplotlib                3.1.1            py37h5429711_0 
```

ll has the same behavior, but didn't crash conda-pack. 

<img width="1076" alt="Screen Shot 2020-01-21 at 14 10 39" src="https://user-images.githubusercontent.com/43654/72834957-d4e7be00-3c57-11ea-8a1b-15d21b753813.png">

**Comment by ericdill** [comment]
I may have had a Python version mismatch

**Comment by mcg1969** [comment]
@ericdill @AlbertDeFusco here's the problem: the symbolic link that exists in Matplotlib is pointing to a library in a _different_ package. So inside the package itself, it's a dangling symbolic link; but when installed in an environment, it's not.

Apparently, the ZIP file approach, as designed, cannot handle symbolic links that don't have matching files. But as Albert's example shows, the .tar.gz approach can.

**Comment by mcg1969** [comment]
@ericdill adding `--zip-symlinks` to your call resolves the issue. From the docs:
```
  --zip-symlinks        Symbolic links aren't supported by the Zip standard,
                        but are supported by *many* common Zip
                        implementations. If set, store symbolic links in the
                        archive, instead of the file referred to by the link.
                        This can avoid storing multiple copies of the same
                        files. *Note that the resulting archive may silently
                        fail on decompression if the ``unzip`` implementation
                        doesn't support symlinks*. Ignored if format isn't
                        ``zip``.
```
I'd still consider this an issue, because zip should error out with a more informative message in this case. Still, zip works if you use this flag.

**Comment by mcg1969** [comment]
Verified as follows:
```
conda create -n ptest matplotlib=3.1.1=py37h5429711_0
conda-pack -n ptest -o /tmp/anaconda3.zip
conda-pack -n ptest -o /tmp/anaconda3.zip --zip-symlinks
cd /tmp
mkdir anaconda3
cd anaconda3
unzip ../anaconda3.zip 
ls -l lib/libtcl.so 
ls -l lib/libtcl8.6.so
```
Will keep this issue open until a PR is offered to provide a better error message. There's no reason why the code cannot detect the use of symlinks in this context and instruct the user to consider --zip-symlinks.

**Comment by mcg1969** [comment]
Here's what you will see now:
```
Collecting packages...
Packing environment at '/home/builder/miniconda3/envs/ptest' to 'ptest.zip'
[                                        ] | 1% Completed |  0.5s
CondaPackError: 
The following conda package file is a symbolic link that does not match an
existing file within the same package:

/home/builder/miniconda3/pkgs/matplotlib-3.1.1-py37h5429711_0/lib/libtcl.so

It is likely this symbolic link points instead to a file that is brought
into the environment by a dependency. Unfortunately, conda-pack does not
support this practice unless the --zip-symlinks option is engaged, or
unless a tar-based archive format is used. See "conda-pack --help" for
more information about the --zip-symlinks option.
```
